src/app/modules/transferencia/transferencia.component.scss
https://github.com/udistrital/sga_documentacion/issues/142
=> feat: udistrital/sga_documentacion#142 Modificación de los componentes para implementar reactividad y confirmar que funcionen las traducciones

package-lock.json, package.json, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/descuento_academico/list-descuento-academico/list-descuento-academico.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/informacion-basica/crud-informacion-familiar/crud-informacion-familiar.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/list-produccion-academica/list-produccion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.ts, src/app/modules/transferencia/transferencia.component.ts
feat: issue#158 arreglo de bugs
=> feat: udistrital/issue#162 arreglo de bugs en el microcliente de inscripcion

.drone.yml, angular.json, package.json
udistrital/sga_documentacion#179
=> feat: Actualización para despliegue udistrital/sga_documentacion#179

src/app/app.module.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-info-persona/crud-info-persona.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/list-experiencia-laboral/list-experiencia-laboral.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.ts, src/assets/i18n/en.json, src/assets/i18n/es.json, src/environments/environment.ts
fix: udistrital/sga_documentacion#199: Arreglo en agregar institución
=> Arreglo en agregar institucion

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/inscripcion-general.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/descuento_academico/list-descuento-academico/list-descuento-academico.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/descuento_academico/view-descuento-academico/view-descuento-academico.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/list-formacion-academica/list-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/view-formacion-academica/view-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/informacion-basica/view-info-persona/view-info-persona.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/list-experiencia-laboral/list-experiencia-laboral.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/view-experiencia-laboral/view-experiencia-laboral.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/perfil/perfil.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/list-produccion-academica/list-produccion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/view-produccion-academica/view-produccion-academica.component.ts, src/app/modules/transferencia/components/solicitud-transferencia/solicitud-transferencia.component.ts, src/app/modules/transferencia/transferencia.component.ts
feat: Ajuste respuesta MID udistrital/sga_documentacion#194
=> feat: Ajuste respuesta MID udistrital/sga_documentacion#194

.husky/build_develop.js, .husky/pre-push, package-lock.json, package.json
feat: Implementación script Husky udistrital/sga_documentacion#239
=> feat: Implementación script Husky udistrital/sga_documentacion#239

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.ts
udistrital/sga_documentacion#223
[Documentacion sga_cliente_inscripcion_mf flujo de consultas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/eslopez_udistrital_edu_co/ETevNMqvu8ZNiBTqGYGxiiMBLE2hIZUOhC3v7n73MvxlXg?e=wHacgX)
=> fix: udistrital/sga_documentacion#223 ajuste select inscripcion

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.ts
(https://github.com/udistrital/sga_documentacion/issues/275) arreglos sobre id programa académico en inscripciones
=> feat: udistrital/sga_documentacion#274

src/app/modules/legalizacion/legalizacion-matricula-aspirante/legalizacion-matricula-aspirante.component.ts, src/app/modules/legalizacion/legalizacion-matricula/legalizacion-matricula.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/inscripcion-general.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/perfil/perfil.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-pregrado/inscripcion-pregrado.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-pregrado/tabs/perfil/perfil.component.ts
udistrital/sga_documentacion#301
=> Reemplaza llamado directo a put de inscripcion por llamado a post de inscripcion mid

src/app/modules/components/dynamic-form/dynamic-form.component.html, src/app/modules/components/dynamic-form/dynamic-form.component.scss, src/app/modules/legalizacion/legalizacion-matricula-aspirante/legalizacion-matricula-aspirante.component.ts, src/app/modules/legalizacion/legalizacion-matricula/legalizacion-matricula.component.ts, src/app/modules/preinscripcion/preinscripcion.module.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-info-persona/crud-info-persona.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.scss, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.ts, src/app/modules/preinscripcion/preinscripcion/preinscripcion.component.ts, src/app/modules/transferencia/components/solicitud-transferencia/solicitud-transferencia.component.html, src/app/modules/transferencia/components/solicitud-transferencia/solicitud-transferencia.component.scss, src/app/modules/transferencia/components/solicitud-transferencia/solicitud-transferencia.component.ts, src/app/modules/transferencia/transferencia.component.html, src/app/modules/transferencia/transferencia.component.scss, src/app/modules/transferencia/transferencia.component.ts, src/app/services/new_nuxeo.service.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
https://github.com/udistrital/sga_documentacion/issues/397
=> feat: udistrital/sga_documentacion#397 Ajuste de funcionamiento y estilos del microcliente de inscripción

src/app/modules/components/dynamic-form/dynamic-form.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-info-persona/form-info_persona.ts, src/environments/environment.production.ts
https://github.com/udistrital/sga_documentacion/issues/432
=> feat: udistrital/sga_documentacion#432 Modificacíon apiUrl de producción

src/app/app-routing.module.ts, src/app/modules/legalizacion/legalizacion-matricula-aspirante/legalizacion-matricula-aspirante.component.ts
https://github.com/udistrital/sga_documentacion/issues/418
=> feat: udistrital/sga_documentacion#418 implementacion de paso a paso en pantalla de consulta de estado de aspirante

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/form-formacion_academica.ts, src/app/services/sga_tercero_mid.service.ts, src/app/services/terceros_mid.service.ts, src/environments/environment.development.ts, src/environments/environment.production.ts, src/environments/environment.ts
https://github.com/udistrital/sga_documentacion/issues/450
=> feat: udistrital/sga_documentacion#450 Modificaciones a terceros service para que funcione en pruebas

src/environments/environment.development.ts, src/environments/environment.production.ts
https://github.com/udistrital/sga_documentacion/issues/450
=> feat: udistrital/sga_documentacion#450 Corrección slash faltante

src/app/modules/components/progress-bar/progress-bar.component.html, src/app/modules/components/progress-bar/progress-bar.component.spec.ts, src/app/modules/components/progress-bar/progress-bar.component.ts, src/app/modules/preinscripcion/preinscripcion.module.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/button-payment/button-payment.component.scss, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/informacion-basica/crud-info-caracteristica/crud-info-caracteristica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/informacion-basica/crud-informacion-contacto/crud-informacion-contacto.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.ts, src/app/modules/preinscripcion/preinscripcion/preinscripcion.component.html, src/app/modules/preinscripcion/preinscripcion/preinscripcion.component.scss, src/assets/i18n/en.json, src/assets/i18n/es.json
- Se arregla la consulta del recibo en la tabla de inscripciones.
- Se crea un componente `progress bar` para ser utilizado a lo ancho de la app.
- Se toma el nivel para cargar el componente de `pregrado` o `general`.
- Se ajusta el componente de `informacion basica`.
---
udistrital/sga_documentacion#440
=> Fix: ajustando flujo de preinscripcion en postgrado (1)

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-pregrado/def_tags_por_programa.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-pregrado/inscripcion-pregrado.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-pregrado/inscripcion-pregrado.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-pregrado/tabs/examen_estado/view-examen-estado/view-examen-estado.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-pregrado/tabs/examen_estado/view-examen-estado/view-examen-estado.component.scss, src/assets/i18n/en.json, src/assets/i18n/es.json
https://github.com/udistrital/sga_documentacion/issues/478
=> feat: udistrital/sga_documentacion#478 Modificaciones al cliente de inscripción

src/environments/environment.development.ts, src/environments/environment.production.ts
manament: ajuste version variable terceros mid
=> manament: ajuste version variable terceros mid

src/app/modules/preinscripcion/preinscripcion/components/crud-info-persona/crud-info-persona.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
- Acceder al Status de la respuesta de manera correcta al guardar una nueva inscripcion.
- Consultar los proyectos cuando se selecciona el periodo.
- Acceder a la data de la respuesta de manera correcta.
- Modal para cuando no existen proyectos academicos.
---
udistrital/sga_documentacion#470
=> fix: flujo de inscripcion postgrado (generar nueva inscripcion)

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.scss, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.ts
- En el select de periodo para crear una inscripcion solo se listan periodos activos. 
- Se elimina un select que no tenia ninguna funcionalidad.
---
=> feat: se cargan unicamente los periodos activos 

src/app/services/any.service.ts
- Añadir bearer token en el servicio anyService.
---
=> feat: añadir bearer token en el servicio anyService

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/inscripcion-general.component.ts
mangement: ajuste de petición Update inscripcion-general.component.ts
=> mangement: ajuste de petición Update inscripcion-general.component.ts

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/inscripcion-general.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-pregrado/inscripcion-pregrado.component.ts
management: actualización consumo servicio Update inscripcion-general.component.ts
=> management: actualización consumo servicio Update inscripcion-general.component.ts

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.ts
- Se agrega visualmente el periodo el cual esta tomando la plataforma.
- Se maneja el formulario de preinscripcion usando formgroup.
---
=> refactor: formulario para crear una preinscripcion.

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-pregrado/inscripcion-pregrado.component.ts
management: formulario para crear una preinscripcion.
=> management: formulario para crear una preinscripcion.

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/crud-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/list-formacion-academica/list-formacion-academica.component.ts
=> feat: correccion de los paths

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/list-experiencia-laboral/list-experiencia-laboral.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/view-experiencia-laboral/view-experiencia-laboral.component.ts
management: ajuste de path experencia laboral
=> management: ajuste de path experencia laboral

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/crud-formacion-academica.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/crud-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/form-formacion_academica.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/list-formacion-academica/list-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.ts, src/assets/i18n/en.json
Fix: adición checkbox para formación actual udistrital/sga_documentacion#494
=> Fix: adición checkbox para formación actual udistrital/sga_documentacion#494

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/crud-formacion-academica.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/crud-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/form-formacion_academica.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/list-formacion-academica/list-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.ts, src/assets/i18n/en.json
management: adición checkbox para formación actual udistrital/sga_documentacion#49
=> management: adición checkbox para formación actual udistrital/sga_documentacion#494 

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/crud-formacion-academica.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/crud-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/form-formacion_academica.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/list-formacion-academica/list-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.ts, src/assets/i18n/en.json
Reverts udistrital/sga_cliente_inscripcion_mf#100
=> Revert "Fix: adición checkbox para formación actual udistrital/sga_documentacion#494"

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/crud-formacion-academica.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/crud-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/form-formacion_academica.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/list-formacion-academica/list-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.ts, src/assets/i18n/en.json
management: rever por error en el checkbox
=> management: rever por error en el checkbox

src/app/modules/preinscripcion/preinscripcion/components/crud-info-persona/crud-info-persona.component.ts
=> feat: recarga pagina luego de guardar los datos de informacion basica.

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.ts
=> managment: ajuste de flujo 

src/app/modules/components/dynamic-form/dynamic-form.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/informacion-basica/crud-info-caracteristica-pregrado/crud-info-caracteristica-pregrado.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/informacion-basica/view-info-persona/view-info-persona.component.html
- refactor de alertas.
- Se elimina codigo comentariado
- file, filerev en formularios mini y bysteps se refactorizan en dinamicform
---
=> Fix: preinscripcion bugs 2

src/app/modules/preinscripcion/preinscripcion.module.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/crud-formacion-academica/crud-formacion-academica.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/new-tercero/form_new_tercero.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/crud-idiomas/crud-idiomas.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/list-idiomas/list-idiomas.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/list-idiomas/list-idiomas.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/form-experiencia_laboral.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
- Ajuste de tab de experiencia laboral.
- Ajuste de tab de formacion academica.
- Ajuste de tab de idiomas.
---
=> Fix: preinscripcion bugs 3

src/app/models/documento/soporte_documento_programa.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/inscripcion-general.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/documento-programa/crud-documento-programa/crud-documento-programa.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/documento-programa/list-documento-programa/list-documento-programa.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/documento-programa/view-documento-programa/view-documento-programa.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/propuesta_grado/crud-propuesta-grado/crud-propuesta-grado.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-pregrado/inscripcion-pregrado.component.ts
- Se añade eliminacion logica a soporte_documento_programa en el tab de documentos solicitados
---
udistrital/sga_documentacion#509
=> Fix: preinscripcion bugs 4

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/inscripcion-general.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/inscripcion-general.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/crud-produccion-academica/crud-produccion-academica.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/crud-produccion-academica/crud-produccion-academica.component.scss, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/crud-produccion-academica/crud-produccion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/crud-produccion-academica/form_new_autor.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/list-produccion-academica/list-produccion-academica.component.html, src/app/services/utilidades.service.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
- Se eliminan clases de bostrap que ya no se usan.
- Se agrega progress-bar en la pantalla principal donde se miran los tab de preinscripcion y se ajusta estilo de alerta de la misma vista.
- Ajustada la sincronia para calcular y consultar el progreso en la preinscripcion.
- Ajustado el componente de produccion academica.
---
udistrital/sga_documentacion#509
=> Fix: preinscripcion bugs 5 tab producción académica

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/perfil/view-inscripcion/view-inscripcion.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/crud-produccion-academica/crud-produccion-academica.component.ts
- Se cargan todas las pestañas en el detalle de inscripción aunque no se haya creado la inscripción.
- En la consulta para encontrar terceros en producción académica se usa anyService en vez de HTTP puro, porque anyService ya configura los encabezados de la petición.
---
udistrital/sga_documentacion#509
=> Fix: preinscripcion bugs 6 tab detalle de inscripcion

.drone.yml
management: preinscripcion bugs 6 tab detalle de inscripcion
=> management: preinscripcion bugs 6 tab detalle de inscripcion

src/app/app.module.ts, src/app/modules/components/dynamic-form/dynamic-form.component.html, src/app/modules/preinscripcion/preinscripcion.module.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/inscripcion-general.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/descuento_academico/crud-descuento-academico/crud-descuento-academico.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/new-tercero/new-tercero.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/crud-experiencia-laboral.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/form-experiencia_laboral.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/list-experiencia-laboral/list-experiencia-laboral.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/list-experiencia-laboral/list-experiencia-laboral.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/crud-inscripcion-multiple.component.ts
- Se termina de ajustar el tab de experiencia laboral.
---
=> Fix: preinscripcion bugs 9

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/crud-idiomas/crud-idiomas.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/crud-idiomas/form-idiomas.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/list-idiomas/list-idiomas.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/list-idiomas/list-idiomas.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/shared-state.service.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
- Se implementaron mensajes para el usuario.
- Hay un indicador del examen seleccionado para el examen.
- Se creo un servicio para compartir el estado entre 2 componentes.
---
=> refactor: ajuste del tab de idioma.

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/crud-idiomas/crud-idiomas.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/crud-idiomas/form-idiomas.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/list-idiomas/list-idiomas.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/list-idiomas/list-idiomas.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/shared-state.service.ts, src/assets/i18n/en.json, src/assets/i18n/es.json, src/environments/environment.production.ts
management: ajuste del tab de idioma.
=> management: ajuste del tab de idioma.

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/idiomas/crud-idiomas/crud-idiomas.component.ts
- Se actualiza el estado idiomaExamen en el servicio sharedState luego de guardar un nuevo idioma.
---
=> feat: Actualizar idiomaExamen en sharedState (tab idioma)

src/environments/environment.production.ts
managment: Update environment.production.ts
=> managment: Update environment.production.ts

src/app/modules/components/dynamic-form/dynamic-form.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/crud-produccion-academica/crud-produccion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/propuesta_grado/crud-propuesta-grado/crud-propuesta-grado.component.ts
- No se podia editar de manera correcta las producciones academicas por que los metadatos se enviaban vacios cuando el formulario solo tenia campos de tipo file.
---
=> fix: editar producciones academicas 

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/informacion-basica/view-info-persona/view-info-persona.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/form-experiencia_laboral.ts
- Corregir orden de opciones en formulario de experiencia lab.
- Ajustar estilo del botón en detalle de inscripcion.
---
=> Fix: preinscripcion bugs 10

src/app/modules/components/dialogo-documentos/dialogo-documentos.component.html, src/app/modules/components/dialogo-documentos/dialogo-documentos.component.scss, src/app/modules/components/dialogo-documentos/dialogo-documentos.component.ts, src/app/modules/legalizacion/legalizacion-matricula-aspirante/legalizacion-matricula-aspirante.component.ts, src/app/modules/legalizacion/legalizacion-matricula/legalizacion-matricula.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/constants.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/descuento_academico/view-descuento-academico/view-descuento-academico.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/documento-programa/view-documento-programa/view-documento-programa.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/formacion-academica/view-formacion-academica/view-formacion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/informacion-basica/view-info-persona/view-info-persona.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/informacion-basica/view-info-persona/view-info-persona.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/crud-experiencia-laboral/form-experiencia_laboral.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/laboral/view-experiencia-laboral/view-experiencia-laboral.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/perfil/perfil.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/produccion-academica/view-produccion-academica/view-produccion-academica.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/propuesta_grado/view-propuesta-grado/view-propuesta-grado.component.ts
- Mejora de ui en la visualizacion de documentos en el tab de detalle de inscripcion.
- Se implementa constante para manejar estado `POR_DEFINIR`,`APROBADO`,`NO_APROBADo`.
---
=> Fix: preinscripcion bugs 11

src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/informacion-basica/view-info-persona/view-info-persona.component.ts, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/perfil/perfil.component.html, src/app/modules/preinscripcion/preinscripcion/components/crud-inscripcion-multiple/components/inscripcion-general/tabs/perfil/perfil.component.ts
- Cada subcomponente carga su informacion y emite un evento `completed`, `failed`, `start`. Se edito la funcion para cuando emita el evento `failed` continue con el siguiente tag o subcomponente.
---
udistrital/sga_documentacion#535
=> fix: ajuste para cargar toda la suite.
